version: '3.8'

services:
  db:
    image: "postgres:14-alpine"
    ports: 
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}"
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5  

  client:
    depends_on: 
      db:
        condition: service_healthy
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
      - REACT_APP_CLIENT_URL=${REACT_APP_CLIENT_URL}
      - REACT_APP_EMAILJS_SERVICE_ID=${REACT_APP_EMAILJS_SERVICE_ID}
      - REACT_APP_EMAILJS_TEMPLATE_ID=${REACT_APP_EMAILJS_TEMPLATE_ID}
      - REACT_APP_EMAILJS_USER_ID=${REACT_APP_EMAILJS_USER_ID}

  server:
    depends_on: 
      db:
        condition: service_healthy
    build: ./src/server
    ports: 
      - "4000:4000"
    restart: unless-stopped
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT_INTERNAL=${POSTGRES_PORT_INTERNAL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
      - REACT_APP_CLIENT_URL=${REACT_APP_CLIENT_URL}

  zabbix_db:
    image: "postgres:14-alpine"
    ports: 
      - "54322:${POSTGRES_PORT_INTERNAL}"
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=postgres
    volumes:
      - zbx_postgres_data:/var/lib/postgresql/data

  zabbix_server:
    image: zabbix/zabbix-server-pgsql:latest
    ports: 
      - "10051:10051"
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DB_SERVER_DBNAME=zabbix
      - DB_SERVER_HOST=zabbix_db
    depends_on:
      - db
      - zabbix_db

  zabbix_web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DB_SERVER_DBNAME=zabbix
      - ZBX_SERVER_HOST=zabbix_server
      - ZBX_SERVER_PORT=10051
    depends_on:
      - db
      - zabbix_db
      - zabbix_server
    
  zabbix_agent:
    image: zabbix/zabbix-agent:latest
    restart: unless-stopped
    environment:
    - ZBX_HOSTNAME=zabbix_test
    - ZBX_SERVER_HOST=zabbix_server  
    - ZBX_SERVER_PORT=10051       
    - ZBX_HOSTMETADATA=linux    
    ports:
      - "10050:10050"
    depends_on:
      - zabbix_server


volumes:
  postgres_data:
  zbx_postgres_data:
  