version: '3.8'

services:
  client:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
  server:
    build: ./src/server
    ports: 
      - "4000:4000"
    restart: unless-stopped
  